# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
movies = Movie.create([{title: "The Internship", 
                        description: "Billy and Nick are salesmen whose careers have been torpedoed by the digital world. Trying to prove they are not obsolete, they defy the odds by talking their way into a coveted internship at Google, along with a battalion of brilliant college students. But, gaining entrance to this utopia is only half the battle. Now they must compete with a group of the nation's most elite, tech-savvy geniuses to prove that necessity really is the mother of re-invention.",
                        rating: "PG-13",
                        opening_date: "2013-06-07",
                        starring: "Vince Vaughn, Owen Wilson",
                        director: "Shawn Levy",
                        runtime: 119,
                        released_by: "20th Century Fox",
                        genres: "Comedy",
                        three_d: false,
                        online: true,
                        trailer: "https://www.youtube.com/watch?v=cdnoqCViqUo"},
                        {title: "Now You See Me", 
                        description: "During their performances, the world's greatest illusionists known as \"The Four Horsemen\" pull off a series of daring heists against corrupt business leaders. The super-team of illusionists shower the stolen profits on their audiences while staying one step ahead of an elite FBI squad in a game of cat and mouse.",
                        rating: "PG-13",
                        opening_date: "2013-05-31",
                        starring: "Mark Ruffalo, Jesse Eisenberg",
                        director: "Louis Leterrier",
                        runtime: 116,
                        released_by: "Lionsgate Films",
                        genres: "Suspense/Thriller",
                        three_d: false,
                        online: true,
                        trailer: "https://www.youtube.com/watch?v=KzJNYYkkhzc"},
                        {title: "Man of Steel", 
                        description: "Clark Kent, a young reporter, roams the world covering news stories, but returns home to face his destiny - to become Superman.",
                        rating: "PG-13",
                        opening_date: "2013-06-14",
                        starring: "Henry Cavill, Diane Lane",
                        director: "Zack Snyder",
                        runtime: 143,
                        released_by: "Warner Bros. Pictures",
                        genres: "Action/Adventure, SciFi/Fantasy",
                        three_d: true,
                        online: true,
                        trailer: "https://www.youtube.com/watch?v=T6DJcgm3wNY"},
                        {title: "World War Z", 
                        description: "A sober telling of the aftermath of a war fought against a legion of humans who were inflicted with a virus, died and were re-animated into flesh-eating zombies.",
                        rating: "PG-13",
                        opening_date: "2013-06-20",
                        starring: "Brad Pitt, James Badge Dale",
                        director: "Marc Forster",
                        runtime: 116,
                        released_by: "Paramount Pictures",
                        genres: "Action/Adventure",
                        three_d: true,
                        online: true,
                        trailer: "https://www.youtube.com/watch?v=HcwTxRuq-uk"}])